debug: true
# plugins:
#   - meilisync.plugin.Plugin
progress:
  type: file
meilisearch:
  api_url: http://localhost:7700/
  api_key: '6776a1d681ce852a7c71aa10d673809574e4914aac29ceb69012276e51adcc05'
  insert_size: 1000
  insert_interval: 10
source:
  type: mysql
  host: 192.168.1.23 # assuming your MySQL server is running on the same machine as `meilisync`
  port: 3306
  database: 9mois
  user: jojo
  password: "jojo"

sync:
  - table: food
    # index: code
    # full: true
    # fields:
    #   code:
    #   name:
    #   archived:
    #   img: